temp/objects/Ballot__c.object
<CustomObject>
    <label>Ballot</label>
    <nameField>
        <label>Ballot Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ballots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Election__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Election</label>
        <referenceTo>Election__c</referenceTo>
        <relationshipLabel>Ballots</relationshipLabel>
        <relationshipName>Ballots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Ballot__c/fields/Ballot_Initiative__c.field-meta.xml
<CustomField>
    <fullName>Ballot_Initiative__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ballot Initiative</label>
    <referenceTo>Ballot_Initiative__c</referenceTo>
    <relationshipLabel>Ballots</relationshipLabel>
    <relationshipName>Ballots</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

temp/objects/Ballot_Initiative__c.object
<CustomObject>
    <description>These are the actual things that will be voted upon.</description>
    <label>Ballot Initiative</label>
    <nameField>
        <label>Ballot Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ballot Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Election__c</fullName>
        <label>Election</label>
        <referenceTo>Election__c</referenceTo>
        <relationshipLabel>Ballot Initiatives</relationshipLabel>
        <relationshipName>Ballot_Initiatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Selections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Selections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Candidates__c</fullName>
        <label>Number of Candidates</label>
        <summaryForeignKey>Ballot_Selection__c.Ballot_Initiative__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Votes_Allowed__c</fullName>
        <description>Maximum number of votes permitted for this office.</description>
        <inlineHelpText>Maximum number of votes allowed for this initiative.</inlineHelpText>
        <label>Votes Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/objects/Ballot_Selection__c.object
<CustomObject>
    <description>The individual choices for each initiative.</description>
    <label>Ballot Selection</label>
    <nameField>
        <label>Ballot Selection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ballot Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ballot_Initiative__c</fullName>
        <label>Ballot Initiative</label>
        <referenceTo>Ballot_Initiative__c</referenceTo>
        <relationshipLabel>Ballot Selections</relationshipLabel>
        <relationshipName>Ballot_Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate_Profile__c</fullName>
        <label>Candidate Profile</label>
        <referenceTo>Candidate_Profile__c</referenceTo>
        <relationshipLabel>Ballot Selections</relationshipLabel>
        <relationshipName>Ballot_Selections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

temp/objects/Candidate_Profile__c.object
<CustomObject>
    <label>Candidate Profile</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ballot_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ballot Initiative</label>
        <referenceTo>Ballot_Initiative__c</referenceTo>
        <relationshipLabel>Candidate Profiles</relationshipLabel>
        <relationshipName>Candidate_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/Election__c.object
<CustomObject>
    <description>Holds information about elections.</description>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Vote__c.object
<CustomObject>
    <label>Vote</label>
    <nameField>
        <label>Vote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Affirmative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Affirmative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ballot_Id__c</fullName>
        <label>Ballot Id</label>
        <referenceTo>Ballot__c</referenceTo>
        <relationshipLabel>Votes</relationshipLabel>
        <relationshipName>Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ballot_Initiative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Ballot Initiative</label>
        <referenceTo>Ballot_Initiative__c</referenceTo>
        <relationshipLabel>Votes</relationshipLabel>
        <relationshipName>Votes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate_Profile__c</referenceTo>
        <relationshipLabel>Votes</relationshipLabel>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/VotingController.cls
public with sharing class VotingController 
{
  public List<Vote__c> votesForSubmission { get;set; }
  public String pageVoterId { get;set; }
public String ballotInitiativeTitle { get;set; }
  public boolean isVoterIdSearchVisible { get;set; }
  public boolean isElectionVisible { get;set; }
  public boolean isVoteVerificationVisible { get;set; }
  public boolean isNextDisabled { get;set; }
  public boolean isPreviousDisabled { get;set; }
  public boolean isVoteInError { get;set; }
  private Ballot__c ballot;
  private Ballot_Initiative__c currentInitiative;
  private Integer initiativeCount;
  private Integer intCurrentInitiative;
  private Id currentInitiativeId;
  private String setFocusId;
  private List<Ballot_Initiative__c> ballotInitiatives;
  private map<id, List<Vote__c>> votesByInitiativeId;
  private Map<Id, List<VotingSelection>> votingSelectionsByInitiativeId;

  public VotingController()
  {
    this.votingSelectionsByInitiativeId = new Map<Id, List<VotingSelection>>();  
    votesForSubmission = new List<Vote__c>();
    isVoterIdSearchVisible = true;
    isElectionVisible = false;
    isVoteInError = false;
    ballotInitiativeTitle = '';
    setFocusId = 'initiativeTitle';
    String urlVoterId = ApexPages.currentPage().getParameters().get('voterId');
    if(!String.isBlank(urlVoterId))
    {
      pageVoterId = urlVoterId;
      PageReference findBallotPage = findBallot();
    }  // End if urlVoterId is not blank
  }  // End constructor

  public List<VotingSelection> getInitiativeSelections()
  {
    return votingSelectionsByInitiativeId.get(currentInitiativeId);
  }  // End initiativeSelections getter method
  public void setInitiativeSelections(List<VotingSelection> newVotingSelections)
  {
    List<VotingSelection> internalVotingSelections = votingSelectionsByInitiativeId.get(currentInitiativeId);
    internalVotingSelections.clear();
    internalVotingSelections.addAll(newVotingSelections);
  }  // End InitiativeSelections setter method
  public String getSetFocusId()
  {
    return setFocusId;
  }  // End setFocusId getter method
  public Integer getVotesAllowed()
  {
    return currentInitiative.Votes_Allowed__c.intValue();
  }  // End votesAllowed getter method
  public PageReference findBallot()
  {
    List<Ballot__c> databaseBallots = [select Id,Name,Election__c from Ballot__c where Name like :pageVoterId];
    if(databaseBallots.isEmpty())
    {
      ApexPages.Message searchError = new ApexPages.Message(ApexPages.Severity.ERROR, 'Your ballot could not be located!', '', 'voterIdInput');
    }  // End if databaseBallots is empty
    else
    {
      ballot = databaseBallots[0];
     isElectionVisible = true;
      isVoterIdSearchVisible = false;
      votesByInitiativeId = new Map<id, List<Vote__c>>();
      for(Vote__c vote : [select Id,Name,Affirmative__c,Ballot_Initiative__c,Candidate__c from Vote__c where Ballot_Id__c = :ballot.Id])
      {
          List<Vote__c> votesByInitiative = votesByInitiativeId.get(vote.Ballot_Initiative__c);
          if(votesByInitiative == null)
          {
            votesByInitiativeId.put(vote.Ballot_Initiative__c, new List<Vote__c>());
          }  // End if votesByInitiative is null
          votesByInitiativeId.get(vote.Ballot_Initiative__c).add(vote);
      }  // End votes loop

      fetchBallotInitiatives(ballot.Election__c);
      renderCurrentInitiative();
    }  // End else databaseBallots is not empty
    return null;
  }  // End findBallot method
  public PageReference renderNext()
  {
    intCurrentInitiative++;
    if(intCurrentInitiative >= initiativeCount)
    {
      isNextDisabled = true;
      intCurrentInitiative = (initiativeCount - 1);
    }  // End if intCurrentInitiative greater or equal to intiaitiveCount
    return renderCurrentInitiative();
  }  // End renderNext method
  public PageReference renderPrevious()
  {
    intCurrentInitiative--;
    if(intCurrentInitiative < 0)
    {
      isPreviousDisabled = true;
    intCurrentInitiative = 0;
    }  // End if intCurrentInitiative less than 0
    return renderCurrentInitiative();
  }  // End renderPrevious method
  public PageReference renderCurrentInitiative()
  {
    currentInitiative = ballotInitiatives[intCurrentInitiative];
    currentInitiativeId = currentInitiative.Id;
    ballotInitiativeTitle = currentInitiative.Name;
    if(intCurrentInitiative > 0)
    {
      isPreviousDisabled = false;
    }  // End if intCurrentInitiative is not 0
    else
    {
      isPreviousDisabled = true;
    }  // End else intCurrentInitiative is 0
    if((intCurrentInitiative + 1) < initiativeCount)
    {
      isNextDisabled = false;
    }  // End if intCurrentInitiative +1 is less than initiativeCount
    else 
    {
      isNextDisabled = true;
    }  // End else disable Next
    return null;
  }  // End renderCurrentInitiative method
  public PageReference displayVotes()
  {
    isVoteVerificationVisible = true;
    isElectionVisible = false;
    for(List<VotingSelection> votingSelections : votingSelectionsByInitiativeId.values())
    {
      for(VotingSelection votingSelection : votingSelections)
      {
        Vote__c newVote = new Vote__c();
        newVote.Name = votingSelection.voteTitle;
        newVote.Ballot_Id__c = votingSelection.ballotId;
        newVote.Ballot_Initiative__c = votingSelection.ballotInitiativeId;
        if(votingSelection.candidateId == null)
        {
            newVote.Affirmative__c = votingSelection.Vote;
        }  // End if voteSelection does not have a candidate assigned
        else
        {
          newVote.Candidate__c = votingSelection.CandidateId;
        }  // End else a candidate was assigned
        votesForSubmission.add(newVote);
      }  // End votingSelection loop
    }  // End VotingSelections list loop
    return null;
  }  // End displayVotes method
  public PageReference validate()
  {
    Ballot_Initiative__c ballotInitiative = ballotInitiatives[intCurrentInitiative];
    Integer intNumChosenVotes = 0;
    String errorString = 'You may only check ' + ballotInitiative.Votes_Allowed__c + ' items.';
    ApexPages.Message voteErrorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, errorString);
    for(VotingSelection votingSelection : votingSelectionsByInitiativeId.get(currentInitiativeId))
    {
      if(votingSelection.vote)
      {
        intNumChosenVotes++;
      }  // End if vote selected
    }  // End votingSelections loop
    if(intNumChosenVotes > ballotInitiative.Votes_Allowed__c)
    {
      isVoteInError = true;
      ApexPages.addMessage(voteErrorMessage);
    }  // End if intNumChosenVotes is greater than votes allowed
    return null;
  }  // End validate method
  public PageReference submitVote()
    {
    try 
    {
      upsert votesForSubmission;
    }  // End try to upsert
    catch(Exception e)
    {

    }  // End catch exception
    return null;
    }  // End submitVote method
  private void fetchBallotInitiatives(Id electionId)
  {
    ballotInitiatives = [select Id,Name,Description__c,Election__c,Has_Selections__c,Number_of_Candidates__c,Votes_Allowed__c, 
     (select Id,Name,Candidate_Profile__c from Ballot_Selections__r)
    from Ballot_Initiative__c where Election__c = :electionId];
    initiativeCount = ballotInitiatives.size();
    intCurrentInitiative = 0;
    for(Ballot_Initiative__c ballotInitiative : ballotInitiatives)
    {
      List<VotingSelection> votingSelections = votingSelectionsByInitiativeId.get(ballotInitiative.Id);
      if(votingSelections == null)
      {
        votingSelectionsByInitiativeId.put(ballotInitiative.Id, new List<VotingSelection>());
      }  // End if votingSelections is null
      if(ballotInitiative.Has_Selections__c)
      {
        for(Ballot_Selection__c ballotSelection : ballotInitiative.Ballot_Selections__r)
        {
          votingSelectionsByInitiativeId.get(ballotInitiative.Id).add(new VotingSelection(false, ballotSelection.Name, ballot.Id, ballotInitiative.Id, ballotSelection.Candidate_Profile__c));
        }  // End ballotSelections loop
      }  // End if has_selections is true
      else {
        votingSelectionsByInitiativeId.get(ballotInitiative.Id).add(new VotingSelection(false, ballotInitiative.Name, ballot.Id, ballotInitiative.Id));
      }  // End else This is a single option Initiative
    }  // End ballot initiatives loop
  }  // End fetchBallotInitiatives

  public class VotingSelection
  {
    public boolean vote { get;set; }
    public String voteTitle { get;set; }
  public String ballotId { get;set; }
  public String ballotInitiativeId { get;set; }
  public String candidateId { get;set; }
    //public String voteId { get;set; }

    public VotingSelection()
    {
      this.vote = false;
      this.voteTitle = '';
    }  // End default constructor
    public VotingSelection(boolean chosenVote, String paramVoteTitle, String paramBallotId, String paramBallotInitiativeId)
    {
      this.vote = chosenVote;
      this.voteTitle = paramVoteTitle;
      this.ballotId = paramBallotId;
      this.ballotInitiativeId = paramBallotInitiativeId;
    }  // End constructor method
    public VotingSelection(boolean chosenVote, String paramVoteTitle, String paramBallotId, String paramBallotInitiativeId, String paramCandidateId)
    {
      this.vote = chosenVote;
      this.voteTitle = paramVoteTitle;
      this.ballotId = paramBallotId;
      this.ballotInitiativeId = paramBallotInitiativeId;
      this.candidateId = paramCandidateId;
    }  // End constructor method
  }  // End class VotingSelection
}  // End class VotingController