temp/objects/Ballot_Initiative__c.object
<CustomObject>
    <description>These are the actual things that will be voted upon.</description>
    <label>Ballot Initiative</label>
    <nameField>
        <label>Ballot Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ballot Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Election__c</fullName>
        <label>Election</label>
        <referenceTo>Election__c</referenceTo>
        <relationshipLabel>Ballot Initiatives</relationshipLabel>
        <relationshipName>Ballot_Initiatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Selections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Selections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Votes_Allowed__c</fullName>
        <description>Maximum number of votes permitted for this office.</description>
        <inlineHelpText>Maximum number of votes allowed for this initiative.</inlineHelpText>
        <label>Votes Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/objects/Ballot_Selection__c.object
<CustomObject>
    <description>The individual choices for each initiative.</description>
    <label>Ballot Selection</label>
    <nameField>
        <label>Ballot Selection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ballot Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ballot_Initiative__c</fullName>
        <label>Ballot Initiative</label>
        <referenceTo>Ballot_Initiative__c</referenceTo>
        <relationshipLabel>Ballot Selections</relationshipLabel>
        <relationshipName>Ballot_Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate_Profile__c</fullName>
        <label>Candidate Profile</label>
        <referenceTo>Candidate_Profile__c</referenceTo>
        <relationshipLabel>Ballot Selections</relationshipLabel>
        <relationshipName>Ballot_Selections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

temp/objects/Candidate_Profile__c.object
<CustomObject>
    <label>Candidate Profile</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ballot_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ballot Initiative</label>
        <referenceTo>Ballot_Initiative__c</referenceTo>
        <relationshipLabel>Candidate Profiles</relationshipLabel>
        <relationshipName>Candidate_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Candidate Profiles</relationshipLabel>
        <relationshipName>Candidate_Profiles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/Election__c.object
<CustomObject>
    <description>Holds information about elections.</description>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of the election</description>
        <label>End  Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The time at which the system will stop accepting votes.</description>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the election is open for voting.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
</CustomObject>

temp/objects/Member__c.object
<CustomObject>
    <description>Connects Teams to contacts with the year they are a part of any particular team.</description>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The person data associated with this team member.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>The team to which this member is associated.</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year this team member is a part of the team. This information can be confirmed by the roster entries to the NBBA each year.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing account for this team.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/VotingTest.cls
@isTest
private class VotingTest
{
  @testSetup static void setup()
  {
    Account nbbaAccount = new Account(Name='NBBA');
    insert nbbaAccount;
    // Insert contacts
    List<Contact> contacts = new List<Contact>();
    for(Integer i = 0; i < 3; i++)
    {
      Contact playerContact = new Contact(FirstName='player', LastName=i.format(), Account=nbbaAccount);
      contacts.add(playerContact);
    }  // End Contacts loop
    insert contacts;
    // Create teams
    List<Team__c> teams = new List<Team__c>();
    for(Integer i = 0; i < 3; i++)
    {
      Team__c team = new Team__c();
      team.Name = i.format();
      team.Account__c = nbbaAccount.Id;
      teams.add(team);
    }  // End teams loop
    insert teams;
    // Create Members
    List<Member__c> members = new List<Member__c>();
    for(Integer i = 0; i < 3; i++)
    {
      Member__c member = new Member__c();
      member.Team__c = teams[i].Id;
      member.Contact__c = contacts[i].Id;
      member.Year__c = '2019';
      member.Name = contact.Name + ' ' + member.Team__r.Name + ' ' + member.Year__c;
      members.add(member);
    }  // End member method
    insert members;
    // Create Candidates
    List<Candidate_Profile__c> candidates = new List<Candidate_Profile__c>();
    for(Contact contact : contacts)
    {
      Candidate_Profile__c candidate = new Candidate_Profile__c();
      candidate.Name = contact.Name;
      candidate.Contact__c = contact.Id;
      candidates.add(candidate);
    }
    // Create Election__c
    Election__c election = new election__c();
    election.name = 'test election';
    election.start_Date__c = System.today();
    election.Start_Time__c = System.now().time();
    election.End_Date__c = System.today();
    election.End_Time__c = System.now().time().addHours(1);
    insert election;
    // Create Ballot Initiatives
    List<Ballot_initiative__c> ballotInitiatives = new List<Ballot_Initiative__c>();
    for(Integer i = 0; i < 3; i++)
    {
      Ballot_Initiative__c ballotInitiative = new Ballot_Initiative__c();
      BallotInitiative.Name = i.format();
      ballotInitiative.Description__c = 'My long descriptive speech';
      ballotInitiative.Election__c = election.Id;
      ballotInitiative.Has_Selections__c = True;
      ballotInitiative.Votes_Allowed__c = 1;
       BallotInitiatives.add(ballotInitiative);
    }  // End teams loop
    ballotInitiatives[1].Votes_Allowed__c = 2;
    ballotInitiatives[2].Has_Selections__c = false;
    ballotInitiatives[2].Description__c = 'This is a yes/no question.';
    insert ballotInitiatives;
    // Create Ballot_Selection__c
    List<Ballot_Selection__c> ballotSelections = new List<Ballot_Selection__c>();
    for(Candidate_Profile__c candidate : candidates)
    {
      for(Integer i = 0; i < 2; i++)
      {
        Ballot_Selection__c ballotSelection = new Ballot_Selection__c();
        ballotSelection.Ballot_Initiative__c = ballotInitiatives[i].Id;
        ballotSelection.Candidate_Profile__c = candidate.Id;
        ballotSelection.Name = candidate.Name;
        ballotSelections.add(ballotSelection);
      }  // End double for loop
    }  // End candidates loop
    insert ballotSelections;
  }  // End setup method
  @isTest static void testSearchField()
  {
    
  }  // End testSearchField method
}  // End VotingTest class