temp/objects/Member__c.object
<CustomObject>
    <description>Connects Teams to contacts with the year they are a part of any particular team.</description>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The person data associated with this team member.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>The team to which this member is associated.</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year this team member is a part of the team. This information can be confirmed by the roster entries to the NBBA each year.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Tournament__c.object
<CustomObject>
    <description>Holds information about a tournament</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Tournament_Stat__c.object
<CustomObject>
    <description>Holds final tournament statistics for each player.</description>
    <fields>
        <fullName>At_Bats__c</fullName>
        <description>The number of times a player has been at bat.</description>
        <label>At Bats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the contact of the team member.</description>
        <label>Member Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Games__c</fullName>
        <description>The number of games a player participated in.</description>
        <label>Games</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup relationship to the member object.</description>
        <label>Membership</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player_Name__c</fullName>
        <description>The name of the player</description>
        <label>Player Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Put_Outs__c</fullName>
        <description>The number of put outs a player has earned.</description>
        <label>Put Outs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Runs__c</fullName>
        <description>The number of runs scored.</description>
        <label>Runs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Strike_Outs__c</fullName>
        <description>The number of times a player strikes out.</description>
        <label>Strike Outs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Name of the player&apos;s team.</description>
        <label>Team Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The team to which this tournament stat is applied.</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The tournament to which this stat applies.</description>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year of this tournament</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Tournament Stat</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/TournamentStatBatchProcess.cls
public class TournamentStatBatchProcess implements Database.Batchable<sObject>
{
  private String queryString;
  private Set<Id> tournamentStatIds;
  private String whereClause;
  private String andClause;

  public TournamentStatBatchProcess()
  {
    initializeClassVariables();
  }  // End default constructor
  public TournamentStatBatchProcess(List<Tournament_Stat__c> tournamentStats)
  {
    initializeClassVariables();
    for(Tournament_Stat__c ts : tournamentStats)
    {
      tournamentStatIds.add(ts.Id);
    }  // End tournamentStats loop
    if(!tournamentStatIds.isEmpty())
    {
      queryString += andClause;
    }  // End if tournamentStatIds is not empty
  }  // End Constructor
  private void initializeClassVariables()
  {
    tournamentStatIds = new Set<Id>();
    queryString = 'select Id,Name,At_Bats__c,Games__c,Contact__c,Player_Name__c,Member__c,Put_Outs__c,Runs__c,Strike_Outs__c,Team__c,Team_Name__c,Tournament__c,Year__c from Tournament_Stat__c';
    whereClause = ' where (Team__c = null OR Tournament__c = null OR Member__c = null OR Contact__c = null)';
    andClause = ' AND Id in :tournamentStatIds';
    queryString += whereClause;
  }  // EndinitializeClassVariables method
  public Database.QueryLocator start(Database.batchableContext bc)
  {
    return Database.getQueryLocator(queryString);
  }  // End start method
  public void execute(Database.BatchableContext bc, List<Tournament_Stat__c> tournamentStats)
  {
    update TournamentStatService.databaseUpdate(tournamentStats);
  }  // End execute method
  public void finish(Database.BatchableContext bc)
  {
    AsyncApexJob a = [select Id,Status,NumberOfErrors,JobItemsProcessed,TotalJobItems,CreatedBy.Email from AsyncApexJob where Id = :bc.getJobId()];
    Messaging.SingleEmailMessage mail = new  Messaging.SingleEmailMessage();
    String[] toAddresses = new String[] {a.CreatedBy.Email};
    mail.setToAddresses(toAddresses);
    mail.setSubject('Tournament Stat Processing ' + a.Status);
    mail.setPlainTextBody('The batch processed ' + a.TotalJobItems + ' records, with ' + a.NumberOfErrors + ' failures.');
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
  }  // End finish method
}  // End TournamentStatBatchProcess class