temp/objects/Member__c.object
<CustomObject>
    <description>Connects Teams to contacts with the year they are a part of any particular team.</description>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Team__c</fullName>
        <description>The team to which this member is associated.</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year this team member is a part of the team. This information can be confirmed by the roster entries to the NBBA each year.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Tournament__c.object
<CustomObject>
    <description>Holds information about a tournament</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Tournament_Stat__c.object
<CustomObject>
    <description>Holds final tournament statistics for each player.</description>
    <fields>
        <fullName>At_Bats__c</fullName>
        <description>The number of times a player has been at bat.</description>
        <label>At Bats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Games__c</fullName>
        <description>The number of games a player participated in.</description>
        <label>Games</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup relationship to the member object.</description>
        <label>Membership</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player_Name__c</fullName>
        <description>The name of the player</description>
        <label>Player Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Put_Outs__c</fullName>
        <description>The number of put outs a player has earned.</description>
        <label>Put Outs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Runs__c</fullName>
        <description>The number of runs scored.</description>
        <label>Runs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Strike_Outs__c</fullName>
        <description>The number of times a player strikes out.</description>
        <label>Strike Outs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Name of the player&apos;s team.</description>
        <label>Team Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The team to which this tournament stat is applied.</description>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The tournament to which this stat applies.</description>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Tournament Stats</relationshipLabel>
        <relationshipName>Tournament_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year of this tournament</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Tournament Stat</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MembershipServiceTest.cls
@isTest
private class MembershipServiceTest
{

  static testMethod void myUnitTest()
  {
    Account nbbaAccount = new Account(Name = 'National Beep Baseball Association');
    insert nbbaAccount;
    //Tournament__c tournamentWorldSeries2016 = new Tournament__c(Name = 'World Series 2016');
    //insert tournamentWorldSeries2016;
    List<Tournament_Stat__c> tournamentStats = new List<Tournament_Stat__c>();
    for(Integer i = 0; i < 200; i++)
    {
      Tournament_Stat__c testStat = new Tournament_Stat__c();
      testStat.Name = 'World Series 2016';
      testStat.At_Bats__c = 17.0;
      testStat.Games__c = 7.0;
      testStat.Player_Name__c = 'Adam Rodenbeck';
      testStat.Put_Outs__c = 5.0;
      testStat.Runs__c = 7.0;
      testStat.Strike_Outs__c = 0.0;
      testStat.Team_Name__c = 'Indy Thunder';
      testStat.Year__c = '2016';
      tournamentStats.add(testStat);
    }  // End 200 count for loop

    Team__c newTeam = new Team__c(Name='BCA');
    insert newTeam;
    tournamentStats[1].Player_Name__c = 'Vergil Flowers';
    tournamentStats[2].Player_Name__c = 'Vergil Flowers';
    tournamentStats[3].Year__c = '2015';
    tournamentStats[3].Name = 'World Series 2015';
    tournamentStats[3].Team_Name__c = 'BCA';
    tournamentStats[3].Player_Name__c = 'Lucas Davenport';
    Test.startTest();
      insert tournamentStats;
      //TournamentStatService.databaseUpdate(tournamentStats);
      TournamentStatBatchProcess bp = new TournamentStatBatchProcess();
      Id jobId = Database.executeBatch(bp);
    Test.stopTest();
    List<Contact> testContacts = [select Id,Name from Contact];
    List<Team__c> testTeams = [select Id,Name from Team__c];
    List<Member__c> testMembers = [select Id,Name from Member__c];
    List<Tournament__c> testTournaments = [select Id,Name from Tournament__c];
    System.assertEquals(3, testContacts.size());
    System.assertEquals(2, testTeams.size());
    System.assertEquals(3, testMembers.size());
    System.assertEquals(2, testTournaments.size());
  }  // End unit test method
}  // End test class